spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sandbox-spring-native}
    username: ${DB_USERNAME:sandbox-spring-native}
    hikari:
      connection-timeout: ${DB_CONNECTION_TIMEOUT_MS:10000}
  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create-drop}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
logging:
  level:
    root: info
    com.dburyak: debug
